/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as AuthenticatedLearnEnrollmentIdRouteImport } from './routes/_authenticated/learn.$enrollmentId'
import { Route as AuthenticatedAdminTenantSlugRouteImport } from './routes/_authenticated/admin.$tenantSlug'
import { Route as AuthenticatedAdminTenantSlugIndexRouteImport } from './routes/_authenticated/admin.$tenantSlug.index'
import { Route as TSlugCoursesCourseSlugRouteImport } from './routes/t.$slug.courses.$courseSlug'
import { Route as AuthenticatedAdminTenantSlugStudentsRouteImport } from './routes/_authenticated/admin.$tenantSlug.students'
import { Route as AuthenticatedAdminTenantSlugSettingsRouteImport } from './routes/_authenticated/admin.$tenantSlug.settings'
import { Route as AuthenticatedAdminTenantSlugCoursesRouteImport } from './routes/_authenticated/admin.$tenantSlug.courses'
import { Route as AuthenticatedAdminTenantSlugCoursesCourseIdRouteImport } from './routes/_authenticated/admin.$tenantSlug.courses.$courseId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugRoute,
} as any)
const AuthenticatedLearnEnrollmentIdRoute =
  AuthenticatedLearnEnrollmentIdRouteImport.update({
    id: '/learn/$enrollmentId',
    path: '/learn/$enrollmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTenantSlugRoute =
  AuthenticatedAdminTenantSlugRouteImport.update({
    id: '/admin/$tenantSlug',
    path: '/admin/$tenantSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTenantSlugIndexRoute =
  AuthenticatedAdminTenantSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTenantSlugRoute,
  } as any)
const TSlugCoursesCourseSlugRoute = TSlugCoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => TSlugRoute,
} as any)
const AuthenticatedAdminTenantSlugStudentsRoute =
  AuthenticatedAdminTenantSlugStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminTenantSlugRoute,
  } as any)
const AuthenticatedAdminTenantSlugSettingsRoute =
  AuthenticatedAdminTenantSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminTenantSlugRoute,
  } as any)
const AuthenticatedAdminTenantSlugCoursesRoute =
  AuthenticatedAdminTenantSlugCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminTenantSlugRoute,
  } as any)
const AuthenticatedAdminTenantSlugCoursesCourseIdRoute =
  AuthenticatedAdminTenantSlugCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminTenantSlugCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/admin/$tenantSlug': typeof AuthenticatedAdminTenantSlugRouteWithChildren
  '/learn/$enrollmentId': typeof AuthenticatedLearnEnrollmentIdRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/admin/$tenantSlug/courses': typeof AuthenticatedAdminTenantSlugCoursesRouteWithChildren
  '/admin/$tenantSlug/settings': typeof AuthenticatedAdminTenantSlugSettingsRoute
  '/admin/$tenantSlug/students': typeof AuthenticatedAdminTenantSlugStudentsRoute
  '/t/$slug/courses/$courseSlug': typeof TSlugCoursesCourseSlugRoute
  '/admin/$tenantSlug/': typeof AuthenticatedAdminTenantSlugIndexRoute
  '/admin/$tenantSlug/courses/$courseId': typeof AuthenticatedAdminTenantSlugCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn/$enrollmentId': typeof AuthenticatedLearnEnrollmentIdRoute
  '/t/$slug': typeof TSlugIndexRoute
  '/admin/$tenantSlug/courses': typeof AuthenticatedAdminTenantSlugCoursesRouteWithChildren
  '/admin/$tenantSlug/settings': typeof AuthenticatedAdminTenantSlugSettingsRoute
  '/admin/$tenantSlug/students': typeof AuthenticatedAdminTenantSlugStudentsRoute
  '/t/$slug/courses/$courseSlug': typeof TSlugCoursesCourseSlugRoute
  '/admin/$tenantSlug': typeof AuthenticatedAdminTenantSlugIndexRoute
  '/admin/$tenantSlug/courses/$courseId': typeof AuthenticatedAdminTenantSlugCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/_authenticated/admin/$tenantSlug': typeof AuthenticatedAdminTenantSlugRouteWithChildren
  '/_authenticated/learn/$enrollmentId': typeof AuthenticatedLearnEnrollmentIdRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/_authenticated/admin/$tenantSlug/courses': typeof AuthenticatedAdminTenantSlugCoursesRouteWithChildren
  '/_authenticated/admin/$tenantSlug/settings': typeof AuthenticatedAdminTenantSlugSettingsRoute
  '/_authenticated/admin/$tenantSlug/students': typeof AuthenticatedAdminTenantSlugStudentsRoute
  '/t/$slug/courses/$courseSlug': typeof TSlugCoursesCourseSlugRoute
  '/_authenticated/admin/$tenantSlug/': typeof AuthenticatedAdminTenantSlugIndexRoute
  '/_authenticated/admin/$tenantSlug/courses/$courseId': typeof AuthenticatedAdminTenantSlugCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/t/$slug'
    | '/admin/$tenantSlug'
    | '/learn/$enrollmentId'
    | '/t/$slug/'
    | '/admin/$tenantSlug/courses'
    | '/admin/$tenantSlug/settings'
    | '/admin/$tenantSlug/students'
    | '/t/$slug/courses/$courseSlug'
    | '/admin/$tenantSlug/'
    | '/admin/$tenantSlug/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learn/$enrollmentId'
    | '/t/$slug'
    | '/admin/$tenantSlug/courses'
    | '/admin/$tenantSlug/settings'
    | '/admin/$tenantSlug/students'
    | '/t/$slug/courses/$courseSlug'
    | '/admin/$tenantSlug'
    | '/admin/$tenantSlug/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/t/$slug'
    | '/_authenticated/admin/$tenantSlug'
    | '/_authenticated/learn/$enrollmentId'
    | '/t/$slug/'
    | '/_authenticated/admin/$tenantSlug/courses'
    | '/_authenticated/admin/$tenantSlug/settings'
    | '/_authenticated/admin/$tenantSlug/students'
    | '/t/$slug/courses/$courseSlug'
    | '/_authenticated/admin/$tenantSlug/'
    | '/_authenticated/admin/$tenantSlug/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TSlugRoute: typeof TSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/_authenticated/learn/$enrollmentId': {
      id: '/_authenticated/learn/$enrollmentId'
      path: '/learn/$enrollmentId'
      fullPath: '/learn/$enrollmentId'
      preLoaderRoute: typeof AuthenticatedLearnEnrollmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$tenantSlug': {
      id: '/_authenticated/admin/$tenantSlug'
      path: '/admin/$tenantSlug'
      fullPath: '/admin/$tenantSlug'
      preLoaderRoute: typeof AuthenticatedAdminTenantSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$tenantSlug/': {
      id: '/_authenticated/admin/$tenantSlug/'
      path: '/'
      fullPath: '/admin/$tenantSlug/'
      preLoaderRoute: typeof AuthenticatedAdminTenantSlugIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTenantSlugRoute
    }
    '/t/$slug/courses/$courseSlug': {
      id: '/t/$slug/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/t/$slug/courses/$courseSlug'
      preLoaderRoute: typeof TSlugCoursesCourseSlugRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/_authenticated/admin/$tenantSlug/students': {
      id: '/_authenticated/admin/$tenantSlug/students'
      path: '/students'
      fullPath: '/admin/$tenantSlug/students'
      preLoaderRoute: typeof AuthenticatedAdminTenantSlugStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminTenantSlugRoute
    }
    '/_authenticated/admin/$tenantSlug/settings': {
      id: '/_authenticated/admin/$tenantSlug/settings'
      path: '/settings'
      fullPath: '/admin/$tenantSlug/settings'
      preLoaderRoute: typeof AuthenticatedAdminTenantSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminTenantSlugRoute
    }
    '/_authenticated/admin/$tenantSlug/courses': {
      id: '/_authenticated/admin/$tenantSlug/courses'
      path: '/courses'
      fullPath: '/admin/$tenantSlug/courses'
      preLoaderRoute: typeof AuthenticatedAdminTenantSlugCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminTenantSlugRoute
    }
    '/_authenticated/admin/$tenantSlug/courses/$courseId': {
      id: '/_authenticated/admin/$tenantSlug/courses/$courseId'
      path: '/$courseId'
      fullPath: '/admin/$tenantSlug/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminTenantSlugCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminTenantSlugCoursesRoute
    }
  }
}

interface AuthenticatedAdminTenantSlugCoursesRouteChildren {
  AuthenticatedAdminTenantSlugCoursesCourseIdRoute: typeof AuthenticatedAdminTenantSlugCoursesCourseIdRoute
}

const AuthenticatedAdminTenantSlugCoursesRouteChildren: AuthenticatedAdminTenantSlugCoursesRouteChildren =
  {
    AuthenticatedAdminTenantSlugCoursesCourseIdRoute:
      AuthenticatedAdminTenantSlugCoursesCourseIdRoute,
  }

const AuthenticatedAdminTenantSlugCoursesRouteWithChildren =
  AuthenticatedAdminTenantSlugCoursesRoute._addFileChildren(
    AuthenticatedAdminTenantSlugCoursesRouteChildren,
  )

interface AuthenticatedAdminTenantSlugRouteChildren {
  AuthenticatedAdminTenantSlugCoursesRoute: typeof AuthenticatedAdminTenantSlugCoursesRouteWithChildren
  AuthenticatedAdminTenantSlugSettingsRoute: typeof AuthenticatedAdminTenantSlugSettingsRoute
  AuthenticatedAdminTenantSlugStudentsRoute: typeof AuthenticatedAdminTenantSlugStudentsRoute
  AuthenticatedAdminTenantSlugIndexRoute: typeof AuthenticatedAdminTenantSlugIndexRoute
}

const AuthenticatedAdminTenantSlugRouteChildren: AuthenticatedAdminTenantSlugRouteChildren =
  {
    AuthenticatedAdminTenantSlugCoursesRoute:
      AuthenticatedAdminTenantSlugCoursesRouteWithChildren,
    AuthenticatedAdminTenantSlugSettingsRoute:
      AuthenticatedAdminTenantSlugSettingsRoute,
    AuthenticatedAdminTenantSlugStudentsRoute:
      AuthenticatedAdminTenantSlugStudentsRoute,
    AuthenticatedAdminTenantSlugIndexRoute:
      AuthenticatedAdminTenantSlugIndexRoute,
  }

const AuthenticatedAdminTenantSlugRouteWithChildren =
  AuthenticatedAdminTenantSlugRoute._addFileChildren(
    AuthenticatedAdminTenantSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminTenantSlugRoute: typeof AuthenticatedAdminTenantSlugRouteWithChildren
  AuthenticatedLearnEnrollmentIdRoute: typeof AuthenticatedLearnEnrollmentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminTenantSlugRoute:
    AuthenticatedAdminTenantSlugRouteWithChildren,
  AuthenticatedLearnEnrollmentIdRoute: AuthenticatedLearnEnrollmentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TSlugRouteChildren {
  TSlugIndexRoute: typeof TSlugIndexRoute
  TSlugCoursesCourseSlugRoute: typeof TSlugCoursesCourseSlugRoute
}

const TSlugRouteChildren: TSlugRouteChildren = {
  TSlugIndexRoute: TSlugIndexRoute,
  TSlugCoursesCourseSlugRoute: TSlugCoursesCourseSlugRoute,
}

const TSlugRouteWithChildren = TSlugRoute._addFileChildren(TSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TSlugRoute: TSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
