// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrgurvuadqymycoxbbqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZ3VydnVhZHF5bXljb3hiYnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyODA5NzAsImV4cCI6MjA5Nzg1Njk3MH0.j66voiycB7K0c0JcQlGjZtDEZKdBbRetbn0rb4RxGW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});